services:
  - type: web
    name: stripe-split-app
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: PARTNER_ACCOUNT_ID
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
